MDSC-201(P)-Assignment-6
Roll.non:22229


Read a CSV File in R:

```{r}
read_data <- read.csv("airtravel.csv")

print(read_data)
```
Number of Rows and Columns of CSV File in R:

```{r}
# print total number of columns
cat("Total Columns: ", ncol(read_data))

# print total number of rows
cat("Total Rows:", nrow(read_data))
```
Using min() and max() With CSV Files:

```{r}
# return minimum value of 1960 column of airtravel.csv
min_data <- min(read_data$X1960)  
print(min_data)

# return maximum value of 1958 column of airtravel.csv
max_data <- max(read_data$X1958)  
print(max_data)
```
Subset of a CSV File in R:
```{r}
# return subset of csv where number of air 
# traveler in 1958 should be greater than 400
sub_data <- subset(read_data, X1958 > 400) 

print(sub_data)
```

Write Into CSV File in R:

```{r}
dataframe1 <- data.frame (
  Name = c("Juan", "Alcaraz", "Simantha"),
  Age = c(22, 15, 19),
  Vote = c(TRUE, FALSE, TRUE))

# write dataframe1 into file1 csv file
write.csv(dataframe1, "file1.csv")
```

```{r}
read_data2 <- read.csv("file1.csv")

print(read_data2)
```

